
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Button facebookLogInBtn;

	private global::Gtk.Button googleLogInBtn;

	private global::Gtk.Button normalLogInBtn;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Log in to Speaky! - SpeakyClient");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.facebookLogInBtn = new global::Gtk.Button();
		this.facebookLogInBtn.CanFocus = true;
		this.facebookLogInBtn.Name = "facebookLogInBtn";
		this.facebookLogInBtn.UseUnderline = true;
		this.facebookLogInBtn.Label = global::Mono.Unix.Catalog.GetString("Log in with Facebook");
		this.vbox1.Add(this.facebookLogInBtn);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.facebookLogInBtn]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.googleLogInBtn = new global::Gtk.Button();
		this.googleLogInBtn.CanFocus = true;
		this.googleLogInBtn.Name = "googleLogInBtn";
		this.googleLogInBtn.UseUnderline = true;
		this.googleLogInBtn.Label = global::Mono.Unix.Catalog.GetString("Log in with Google");
		this.vbox1.Add(this.googleLogInBtn);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.googleLogInBtn]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.normalLogInBtn = new global::Gtk.Button();
		this.normalLogInBtn.CanFocus = true;
		this.normalLogInBtn.Name = "normalLogInBtn";
		this.normalLogInBtn.UseUnderline = true;
		this.normalLogInBtn.Label = global::Mono.Unix.Catalog.GetString("Log in with username and password");
		this.vbox1.Add(this.normalLogInBtn);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.normalLogInBtn]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 117;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.facebookLogInBtn.Clicked += new global::System.EventHandler(this.OnFacebookLogInBtnClicked);
		this.googleLogInBtn.Clicked += new global::System.EventHandler(this.OnGoogleLogInBtnClicked);
		this.normalLogInBtn.Clicked += new global::System.EventHandler(this.OnNormalLogInBtnClicked);
	}
}
