
// This file has been generated by the GUI designer. Do not modify.
namespace SpeakyClient
{
	public partial class UserInfoWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Image profilePicImage;

		private global::Gtk.Table table1;

		private global::Gtk.Label addressLbl;

		private global::Gtk.Label ageLbl;

		private global::Gtk.Label firstNameLbl;

		private global::Gtk.Label genderLbl;

		private global::Gtk.Label joinDateLbl;

		private global::Gtk.Label lastNameLbl;

		private global::Gtk.Label lastSeenLbl;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SpeakyClient.UserInfoWindow
			this.Name = "SpeakyClient.UserInfoWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("UserInfoWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SpeakyClient.UserInfoWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.profilePicImage = new global::Gtk.Image();
			this.profilePicImage.Name = "profilePicImage";
			this.hbox3.Add(this.profilePicImage);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.profilePicImage]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.addressLbl = new global::Gtk.Label();
			this.addressLbl.Name = "addressLbl";
			this.addressLbl.LabelProp = global::Mono.Unix.Catalog.GetString("<address>");
			this.table1.Add(this.addressLbl);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.addressLbl]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.ageLbl = new global::Gtk.Label();
			this.ageLbl.Name = "ageLbl";
			this.ageLbl.LabelProp = global::Mono.Unix.Catalog.GetString("<age>");
			this.table1.Add(this.ageLbl);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.ageLbl]));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.firstNameLbl = new global::Gtk.Label();
			this.firstNameLbl.Name = "firstNameLbl";
			this.firstNameLbl.LabelProp = global::Mono.Unix.Catalog.GetString("<firstname>");
			this.table1.Add(this.firstNameLbl);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.firstNameLbl]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.genderLbl = new global::Gtk.Label();
			this.genderLbl.Name = "genderLbl";
			this.genderLbl.LabelProp = global::Mono.Unix.Catalog.GetString("<gender>");
			this.table1.Add(this.genderLbl);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.genderLbl]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.joinDateLbl = new global::Gtk.Label();
			this.joinDateLbl.Name = "joinDateLbl";
			this.joinDateLbl.LabelProp = global::Mono.Unix.Catalog.GetString("<joinDate>");
			this.table1.Add(this.joinDateLbl);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.joinDateLbl]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lastNameLbl = new global::Gtk.Label();
			this.lastNameLbl.Name = "lastNameLbl";
			this.lastNameLbl.LabelProp = global::Mono.Unix.Catalog.GetString("<lastname>");
			this.table1.Add(this.lastNameLbl);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.lastNameLbl]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lastSeenLbl = new global::Gtk.Label();
			this.lastSeenLbl.Name = "lastSeenLbl";
			this.lastSeenLbl.LabelProp = global::Mono.Unix.Catalog.GetString("<lastSeen>");
			this.table1.Add(this.lastSeenLbl);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.lastSeenLbl]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox3.Add(this.table1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.table1]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 481;
			this.DefaultHeight = 339;
			this.Show();
		}
	}
}
