
// This file has been generated by the GUI designer. Do not modify.
namespace SpeakyClient
{
	public partial class HomeWindow
	{
		private global::Gtk.HBox hbox2;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Image profilePicImg;

		private global::Gtk.Label nameLbl;

		private global::Gtk.Button googlePlayBtn;

		private global::Gtk.Button appStoreBtn;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView chatsView;

		private global::Gtk.VBox vbox6;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView textview3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Entry entry1;

		private global::Gtk.Button msgSendBtn;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SpeakyClient.HomeWindow
			this.Name = "SpeakyClient.HomeWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("HomeWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SpeakyClient.HomeWindow.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.profilePicImg = new global::Gtk.Image();
			this.profilePicImg.Name = "profilePicImg";
			this.vbox1.Add(this.profilePicImg);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.profilePicImg]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.nameLbl = new global::Gtk.Label();
			this.nameLbl.Name = "nameLbl";
			this.nameLbl.Ypad = 50;
			this.nameLbl.LabelProp = global::Mono.Unix.Catalog.GetString("<username>");
			this.vbox1.Add(this.nameLbl);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.nameLbl]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.googlePlayBtn = new global::Gtk.Button();
			this.googlePlayBtn.CanFocus = true;
			this.googlePlayBtn.Name = "googlePlayBtn";
			this.googlePlayBtn.UseUnderline = true;
			this.googlePlayBtn.Label = global::Mono.Unix.Catalog.GetString("Google Play");
			this.vbox1.Add(this.googlePlayBtn);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.googlePlayBtn]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.appStoreBtn = new global::Gtk.Button();
			this.appStoreBtn.CanFocus = true;
			this.appStoreBtn.Name = "appStoreBtn";
			this.appStoreBtn.UseUnderline = true;
			this.appStoreBtn.Label = global::Mono.Unix.Catalog.GetString("AppStore");
			this.vbox1.Add(this.appStoreBtn);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.appStoreBtn]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox2.Add(this.vbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.chatsView = new global::Gtk.NodeView();
			this.chatsView.CanFocus = true;
			this.chatsView.Name = "chatsView";
			this.GtkScrolledWindow.Add(this.chatsView);
			this.hbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow]));
			w7.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textview3 = new global::Gtk.TextView();
			this.textview3.CanFocus = true;
			this.textview3.Name = "textview3";
			this.GtkScrolledWindow1.Add(this.textview3);
			this.vbox6.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.GtkScrolledWindow1]));
			w9.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.hbox3.Add(this.entry1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entry1]));
			w10.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.msgSendBtn = new global::Gtk.Button();
			this.msgSendBtn.CanFocus = true;
			this.msgSendBtn.Name = "msgSendBtn";
			this.msgSendBtn.UseUnderline = true;
			this.msgSendBtn.Label = global::Mono.Unix.Catalog.GetString("Send message");
			this.hbox3.Add(this.msgSendBtn);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.msgSendBtn]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox6.Add(this.hbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox3]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox2.Add(this.vbox6);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox6]));
			w13.Position = 2;
			this.Add(this.hbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 656;
			this.DefaultHeight = 308;
			this.Show();
		}
	}
}
